/* -*- Mode: C; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * This library is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
#if !defined (__LIBICAL_GLIB_H_INSIDE__) && !defined (LIBICAL_GLIB_COMPILATION)
#error "Only <libical-glib/libical-glib.h> can be included directly."
#endif
*/
#ifndef I_CAL_ENUMS_H
#define I_CAL_ENUMS_H

#include "common-header.h"


G_BEGIN_DECLS




typedef enum {
	I_CAL_NO_COMPONENT = ICAL_NO_COMPONENT,
	I_CAL_ANY_COMPONENT = ICAL_ANY_COMPONENT,
	I_CAL_XROOT_COMPONENT = ICAL_XROOT_COMPONENT,
	I_CAL_XATTACH_COMPONENT = ICAL_XATTACH_COMPONENT,
	I_CAL_VEVENT_COMPONENT = ICAL_VEVENT_COMPONENT,
	I_CAL_VTODO_COMPONENT = ICAL_VTODO_COMPONENT,
	I_CAL_VJOURNAL_COMPONENT = ICAL_VJOURNAL_COMPONENT,
	I_CAL_VCALENDAR_COMPONENT = ICAL_VCALENDAR_COMPONENT,
	I_CAL_VAGENDA_COMPONENT = ICAL_VAGENDA_COMPONENT,
	I_CAL_VFREEBUSY_COMPONENT = ICAL_VFREEBUSY_COMPONENT,
	I_CAL_VALARM_COMPONENT = ICAL_VALARM_COMPONENT,
	I_CAL_XAUDIOALARM_COMPONENT = ICAL_XAUDIOALARM_COMPONENT,
	I_CAL_XDISPLAYALARM_COMPONENT = ICAL_XDISPLAYALARM_COMPONENT,
	I_CAL_XEMAILALARM_COMPONENT = ICAL_XEMAILALARM_COMPONENT,
	I_CAL_XPROCEDUREALARM_COMPONENT = ICAL_XPROCEDUREALARM_COMPONENT,
	I_CAL_VTIMEZONE_COMPONENT = ICAL_VTIMEZONE_COMPONENT,
	I_CAL_XSTANDARD_COMPONENT = ICAL_XSTANDARD_COMPONENT,
	I_CAL_XDAYLIGHT_COMPONENT = ICAL_XDAYLIGHT_COMPONENT,
	I_CAL_X_COMPONENT = ICAL_X_COMPONENT,
	I_CAL_VSCHEDULE_COMPONENT = ICAL_VSCHEDULE_COMPONENT,
	I_CAL_VQUERY_COMPONENT = ICAL_VQUERY_COMPONENT,
	I_CAL_VREPLY_COMPONENT = ICAL_VREPLY_COMPONENT,
	I_CAL_VCAR_COMPONENT = ICAL_VCAR_COMPONENT,
	I_CAL_VCOMMAND_COMPONENT = ICAL_VCOMMAND_COMPONENT,
	I_CAL_XLICINVALID_COMPONENT = ICAL_XLICINVALID_COMPONENT,
	I_CAL_XLICMIMEPART_COMPONENT = ICAL_XLICMIMEPART_COMPONENT
} ICalComponentKind;

typedef enum {
	I_CAL_UNKNOWN_STATUS = ICAL_UNKNOWN_STATUS,
	I_CAL_2_0_SUCCESS_STATUS = ICAL_2_0_SUCCESS_STATUS,
	I_CAL_2_1_FALLBACK_STATUS = ICAL_2_1_FALLBACK_STATUS,
	I_CAL_2_2_IGPROP_STATUS = ICAL_2_2_IGPROP_STATUS,
	I_CAL_2_3_IGPARAM_STATUS = ICAL_2_3_IGPARAM_STATUS,
	I_CAL_2_4_IGXPROP_STATUS = ICAL_2_4_IGXPROP_STATUS,
	I_CAL_2_5_IGXPARAM_STATUS = ICAL_2_5_IGXPARAM_STATUS,
	I_CAL_2_6_IGCOMP_STATUS = ICAL_2_6_IGCOMP_STATUS,
	I_CAL_2_7_FORWARD_STATUS = ICAL_2_7_FORWARD_STATUS,
	I_CAL_2_8_ONEEVENT_STATUS = ICAL_2_8_ONEEVENT_STATUS,
	I_CAL_2_9_TRUNC_STATUS = ICAL_2_9_TRUNC_STATUS,
	I_CAL_2_10_ONETODO_STATUS = ICAL_2_10_ONETODO_STATUS,
	I_CAL_2_11_TRUNCRRULE_STATUS = ICAL_2_11_TRUNCRRULE_STATUS,
	I_CAL_3_0_INVPROPNAME_STATUS = ICAL_3_0_INVPROPNAME_STATUS,
	I_CAL_3_1_INVPROPVAL_STATUS = ICAL_3_1_INVPROPVAL_STATUS,
	I_CAL_3_2_INVPARAM_STATUS = ICAL_3_2_INVPARAM_STATUS,
	I_CAL_3_3_INVPARAMVAL_STATUS = ICAL_3_3_INVPARAMVAL_STATUS,
	I_CAL_3_4_INVCOMP_STATUS = ICAL_3_4_INVCOMP_STATUS,
	I_CAL_3_5_INVTIME_STATUS = ICAL_3_5_INVTIME_STATUS,
	I_CAL_3_6_INVRULE_STATUS = ICAL_3_6_INVRULE_STATUS,
	I_CAL_3_7_INVCU_STATUS = ICAL_3_7_INVCU_STATUS,
	I_CAL_3_8_NOAUTH_STATUS = ICAL_3_8_NOAUTH_STATUS,
	I_CAL_3_9_BADVERSION_STATUS = ICAL_3_9_BADVERSION_STATUS,
	I_CAL_3_10_TOOBIG_STATUS = ICAL_3_10_TOOBIG_STATUS,
	I_CAL_3_11_MISSREQCOMP_STATUS = ICAL_3_11_MISSREQCOMP_STATUS,
	I_CAL_3_12_UNKCOMP_STATUS = ICAL_3_12_UNKCOMP_STATUS,
	I_CAL_3_13_BADCOMP_STATUS = ICAL_3_13_BADCOMP_STATUS,
	I_CAL_3_14_NOCAP_STATUS = ICAL_3_14_NOCAP_STATUS,
	I_CAL_3_15_INVCOMMAND = ICAL_3_15_INVCOMMAND,
	I_CAL_4_0_BUSY_STATUS = ICAL_4_0_BUSY_STATUS,
	I_CAL_4_1_STORE_ACCESS_DENIED = ICAL_4_1_STORE_ACCESS_DENIED,
	I_CAL_4_2_STORE_FAILED = ICAL_4_2_STORE_FAILED,
	I_CAL_4_3_STORE_NOT_FOUND = ICAL_4_3_STORE_NOT_FOUND,
	I_CAL_5_0_MAYBE_STATUS = ICAL_5_0_MAYBE_STATUS,
	I_CAL_5_1_UNAVAIL_STATUS = ICAL_5_1_UNAVAIL_STATUS,
	I_CAL_5_2_NOSERVICE_STATUS = ICAL_5_2_NOSERVICE_STATUS,
	I_CAL_5_3_NOSCHED_STATUS = ICAL_5_3_NOSCHED_STATUS,
	I_CAL_6_1_CONTAINER_NOT_FOUND = ICAL_6_1_CONTAINER_NOT_FOUND,
	I_CAL_9_0_UNRECOGNIZED_COMMAND = ICAL_9_0_UNRECOGNIZED_COMMAND
} ICalRequestStatus;

typedef enum {
	I_CAL_ANY_PROPERTY = ICAL_ANY_PROPERTY,
	I_CAL_ACKNOWLEDGED_PROPERTY = ICAL_ACKNOWLEDGED_PROPERTY,
	I_CAL_ACTION_PROPERTY = ICAL_ACTION_PROPERTY,
	I_CAL_ALLOWCONFLICT_PROPERTY = ICAL_ALLOWCONFLICT_PROPERTY,
	I_CAL_ATTACH_PROPERTY = ICAL_ATTACH_PROPERTY,
	I_CAL_ATTENDEE_PROPERTY = ICAL_ATTENDEE_PROPERTY,
	I_CAL_CALID_PROPERTY = ICAL_CALID_PROPERTY,
	I_CAL_CALMASTER_PROPERTY = ICAL_CALMASTER_PROPERTY,
	I_CAL_CALSCALE_PROPERTY = ICAL_CALSCALE_PROPERTY,
	I_CAL_CAPVERSION_PROPERTY = ICAL_CAPVERSION_PROPERTY,
	I_CAL_CARLEVEL_PROPERTY = ICAL_CARLEVEL_PROPERTY,
	I_CAL_CARID_PROPERTY = ICAL_CARID_PROPERTY,
	I_CAL_CATEGORIES_PROPERTY = ICAL_CATEGORIES_PROPERTY,
	I_CAL_CLASS_PROPERTY = ICAL_CLASS_PROPERTY,
	I_CAL_CMD_PROPERTY = ICAL_CMD_PROPERTY,
	I_CAL_COMMENT_PROPERTY = ICAL_COMMENT_PROPERTY,
	I_CAL_COMPLETED_PROPERTY = ICAL_COMPLETED_PROPERTY,
	I_CAL_COMPONENTS_PROPERTY = ICAL_COMPONENTS_PROPERTY,
	I_CAL_CONTACT_PROPERTY = ICAL_CONTACT_PROPERTY,
	I_CAL_CREATED_PROPERTY = ICAL_CREATED_PROPERTY,
	I_CAL_CSID_PROPERTY = ICAL_CSID_PROPERTY,
	I_CAL_DATEMAX_PROPERTY = ICAL_DATEMAX_PROPERTY,
	I_CAL_DATEMIN_PROPERTY = ICAL_DATEMIN_PROPERTY,
	I_CAL_DECREED_PROPERTY = ICAL_DECREED_PROPERTY,
	I_CAL_DEFAULTCHARSET_PROPERTY = ICAL_DEFAULTCHARSET_PROPERTY,
	I_CAL_DEFAULTLOCALE_PROPERTY = ICAL_DEFAULTLOCALE_PROPERTY,
	I_CAL_DEFAULTTZID_PROPERTY = ICAL_DEFAULTTZID_PROPERTY,
	I_CAL_DEFAULTVCARS_PROPERTY = ICAL_DEFAULTVCARS_PROPERTY,
	I_CAL_DENY_PROPERTY = ICAL_DENY_PROPERTY,
	I_CAL_DESCRIPTION_PROPERTY = ICAL_DESCRIPTION_PROPERTY,
	I_CAL_DTEND_PROPERTY = ICAL_DTEND_PROPERTY,
	I_CAL_DTSTAMP_PROPERTY = ICAL_DTSTAMP_PROPERTY,
	I_CAL_DTSTART_PROPERTY = ICAL_DTSTART_PROPERTY,
	I_CAL_DUE_PROPERTY = ICAL_DUE_PROPERTY,
	I_CAL_DURATION_PROPERTY = ICAL_DURATION_PROPERTY,
	I_CAL_EXDATE_PROPERTY = ICAL_EXDATE_PROPERTY,
	I_CAL_EXPAND_PROPERTY = ICAL_EXPAND_PROPERTY,
	I_CAL_EXRULE_PROPERTY = ICAL_EXRULE_PROPERTY,
	I_CAL_FREEBUSY_PROPERTY = ICAL_FREEBUSY_PROPERTY,
	I_CAL_GEO_PROPERTY = ICAL_GEO_PROPERTY,
	I_CAL_GRANT_PROPERTY = ICAL_GRANT_PROPERTY,
	I_CAL_ITIPVERSION_PROPERTY = ICAL_ITIPVERSION_PROPERTY,
	I_CAL_LASTMODIFIED_PROPERTY = ICAL_LASTMODIFIED_PROPERTY,
	I_CAL_LOCATION_PROPERTY = ICAL_LOCATION_PROPERTY,
	I_CAL_MAXCOMPONENTSIZE_PROPERTY = ICAL_MAXCOMPONENTSIZE_PROPERTY,
	I_CAL_MAXDATE_PROPERTY = ICAL_MAXDATE_PROPERTY,
	I_CAL_MAXRESULTS_PROPERTY = ICAL_MAXRESULTS_PROPERTY,
	I_CAL_MAXRESULTSSIZE_PROPERTY = ICAL_MAXRESULTSSIZE_PROPERTY,
	I_CAL_METHOD_PROPERTY = ICAL_METHOD_PROPERTY,
	I_CAL_MINDATE_PROPERTY = ICAL_MINDATE_PROPERTY,
	I_CAL_MULTIPART_PROPERTY = ICAL_MULTIPART_PROPERTY,
	I_CAL_NAME_PROPERTY = ICAL_NAME_PROPERTY,
	I_CAL_ORGANIZER_PROPERTY = ICAL_ORGANIZER_PROPERTY,
	I_CAL_OWNER_PROPERTY = ICAL_OWNER_PROPERTY,
	I_CAL_PERCENTCOMPLETE_PROPERTY = ICAL_PERCENTCOMPLETE_PROPERTY,
	I_CAL_PERMISSION_PROPERTY = ICAL_PERMISSION_PROPERTY,
	I_CAL_PRIORITY_PROPERTY = ICAL_PRIORITY_PROPERTY,
	I_CAL_PRODID_PROPERTY = ICAL_PRODID_PROPERTY,
	I_CAL_QUERY_PROPERTY = ICAL_QUERY_PROPERTY,
	I_CAL_QUERYLEVEL_PROPERTY = ICAL_QUERYLEVEL_PROPERTY,
	I_CAL_QUERYID_PROPERTY = ICAL_QUERYID_PROPERTY,
	I_CAL_QUERYNAME_PROPERTY = ICAL_QUERYNAME_PROPERTY,
	I_CAL_RDATE_PROPERTY = ICAL_RDATE_PROPERTY,
	I_CAL_RECURACCEPTED_PROPERTY = ICAL_RECURACCEPTED_PROPERTY,
	I_CAL_RECUREXPAND_PROPERTY = ICAL_RECUREXPAND_PROPERTY,
	I_CAL_RECURLIMIT_PROPERTY = ICAL_RECURLIMIT_PROPERTY,
	I_CAL_RECURRENCEID_PROPERTY = ICAL_RECURRENCEID_PROPERTY,
	I_CAL_RELATEDTO_PROPERTY = ICAL_RELATEDTO_PROPERTY,
	I_CAL_RELCALID_PROPERTY = ICAL_RELCALID_PROPERTY,
	I_CAL_REPEAT_PROPERTY = ICAL_REPEAT_PROPERTY,
	I_CAL_REQUESTSTATUS_PROPERTY = ICAL_REQUESTSTATUS_PROPERTY,
	I_CAL_RESOURCES_PROPERTY = ICAL_RESOURCES_PROPERTY,
	I_CAL_RESTRICTION_PROPERTY = ICAL_RESTRICTION_PROPERTY,
	I_CAL_RRULE_PROPERTY = ICAL_RRULE_PROPERTY,
	I_CAL_SCOPE_PROPERTY = ICAL_SCOPE_PROPERTY,
	I_CAL_SEQUENCE_PROPERTY = ICAL_SEQUENCE_PROPERTY,
	I_CAL_STATUS_PROPERTY = ICAL_STATUS_PROPERTY,
	I_CAL_STORESEXPANDED_PROPERTY = ICAL_STORESEXPANDED_PROPERTY,
	I_CAL_SUMMARY_PROPERTY = ICAL_SUMMARY_PROPERTY,
	I_CAL_TARGET_PROPERTY = ICAL_TARGET_PROPERTY,
	I_CAL_TRANSP_PROPERTY = ICAL_TRANSP_PROPERTY,
	I_CAL_TRIGGER_PROPERTY = ICAL_TRIGGER_PROPERTY,
	I_CAL_TZID_PROPERTY = ICAL_TZID_PROPERTY,
	I_CAL_TZNAME_PROPERTY = ICAL_TZNAME_PROPERTY,
	I_CAL_TZOFFSETFROM_PROPERTY = ICAL_TZOFFSETFROM_PROPERTY,
	I_CAL_TZOFFSETTO_PROPERTY = ICAL_TZOFFSETTO_PROPERTY,
	I_CAL_TZURL_PROPERTY = ICAL_TZURL_PROPERTY,
	I_CAL_UID_PROPERTY = ICAL_UID_PROPERTY,
	I_CAL_URL_PROPERTY = ICAL_URL_PROPERTY,
	I_CAL_VERSION_PROPERTY = ICAL_VERSION_PROPERTY,
	I_CAL_X_PROPERTY = ICAL_X_PROPERTY,
	I_CAL_XLICCLASS_PROPERTY = ICAL_XLICCLASS_PROPERTY,
	I_CAL_XLICCLUSTERCOUNT_PROPERTY = ICAL_XLICCLUSTERCOUNT_PROPERTY,
	I_CAL_XLICERROR_PROPERTY = ICAL_XLICERROR_PROPERTY,
	I_CAL_XLICMIMECHARSET_PROPERTY = ICAL_XLICMIMECHARSET_PROPERTY,
	I_CAL_XLICMIMECID_PROPERTY = ICAL_XLICMIMECID_PROPERTY,
	I_CAL_XLICMIMECONTENTTYPE_PROPERTY = ICAL_XLICMIMECONTENTTYPE_PROPERTY,
	I_CAL_XLICMIMEENCODING_PROPERTY = ICAL_XLICMIMEENCODING_PROPERTY,
	I_CAL_XLICMIMEFILENAME_PROPERTY = ICAL_XLICMIMEFILENAME_PROPERTY,
	I_CAL_XLICMIMEOPTINFO_PROPERTY = ICAL_XLICMIMEOPTINFO_PROPERTY,
	I_CAL_NO_PROPERTY = ICAL_NO_PROPERTY
} ICalPropertyKind;


const gchar *	i_cal_enum_reqstat_desc		(ICalRequestStatus stat);
gshort 		i_cal_enum_reqstat_major	(ICalRequestStatus stat);
gshort 		i_cal_enum_reqstat_minor	(ICalRequestStatus stat);
ICalRequestStatus 
		i_cal_enum_num_to_reqstat	(gshort major,
						 gshort minor);
gchar *		i_cal_enum_reqstat_code_r	(ICalRequestStatus stat);

G_END_DECLS

#endif /* I_CAL_ENUMS_H */
